safe: true
timezone: "Europe/Warsaw"
encoding: utf-8
lsi: false
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  gfm_quirks: [paragraph_end]
  gfm_emojis: true
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-merlot
show_downloads: false
title: Konstytucje
description: "Autorzy: Mateusz&nbps;Kasprzak, Szymon&nbps;Marynowski, Michał&nbps;Wójtowicz, Krzysztof&nbps;Jurkowski"